name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.0]

    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: yarn build --if-present

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: www.monster-hash.cn
          port: 21
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_pwd }}
          
          local-dir: ./build/
          server-dir: www/wwwroot/www.monster-hash.cn/my-website/build/
        env:
          CI: true
